project:
  type: website
  output-dir: docs

website:

  title: "DataVizards's Project Lab"

  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Data
        href: data.qmd
      - text: Analysis
        href: analysis.qmd

            
    tools:
      - icon: github
        href: https://github.com/emu-hacettepe-analytics/emu430-fall2023-team-data_vizards

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "The data's journey: Migration, where lines of code traverse the landscapes of analytics."
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: 
      light: sandstone 
      dark: cyborg
    css: styles.css


editor: visual

