project:
  type: website
  output-dir: docs

website:
<<<<<<< HEAD
  title: "Data Vizards Project Lab"
=======
  title: "DataVizards' Project Lab"
>>>>>>> e4409ec36fcf34ee558b03fa4ba4e23dedf35524
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Data
        href: data.qmd
      - text: Analysis
        href: analysis.qmd

            
    tools:
      - icon: github
        href: https://twitter.com

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 430 - Fall 2023" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: 
      light: simplex 
      dark: cyborg
    css: styles.css


editor: visual

