---
title: "Team Data Vizards"
sidebar: false 
---

This is our project webpage.

Please stay tuned to follow our project activities.

This is our template.

# Team Members

1.  [Şadiye Öztürk](https://emu-hacettepe-analytics.github.io/emu430-fall2023-sadiye-1/)

2.  [Melike Nur Kutlusan](https://emu-hacettepe-analytics.github.io/emu430-fall2023-melikekutlusan/)

3.  [Zeynep Tuncaboylu](https://emu-hacettepe-analytics.github.io/emu430-fall2023-zeyneptnc/)

4.  [Beyzanur Nas](https://emu-hacettepe-analytics.github.io/emu430-fall2023-beyzanurnas/)

5.  [Duygu Eken](https://github.com/emu-hacettepe-analytics/emu430-fall2023-dygekn)

6.  [Melek Er](https://github.com/emu-hacettepe-analytics/emu430-fall2023-Meleker.git)

# Project Topic
  We will carry out our project by considering 2021 internal migration data across Türkiye. Our main focus is In Migration of internal cities. In this regard, migration trends between different regions such as Eastern Anatolia, Southeastern Anatolia, Aegean, Marmara will be determined and migration relations between big cities and other cities will be analyzed in detail. The relationship between population density and migration will be determined by examining migration rates, especially in cities with large populations. Migration trends will be evaluated according to age groups, gender, educational status and reasons for migration. (retirement, appointment, etc.) Also, the economic development level of the economic region will be interpreted according to the labor force, household disposable income, number of enterprises, number of housing sales, etc. This comprehensive analysis will guide our project in understanding Turkey's migration situation.
 
# Data Set
